[project]
name = "genkit-tools-sample-flows"
version = "0.1.0"
description = "Tool to run flow tests for Genkit samples"
authors = [{ name = "Google" }]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "genkit",
    "httpx",
    "structlog",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["review_sample_flows.py", "run_single_flow.py"]

[tool.uv.sources]
genkit = { workspace = true }
