# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bump and Tag JS Plugins Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release type
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major
          - prerelease
      preid:
        description: Prerelease identifier
        type: string
        default: rc
        required: true

jobs:
  build:
    name: Version bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v3
      - name: Set up node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      # - name: 'js/plugins/chroma version bump'
      #   uses: 'phips28/gh-action-bump-version@master'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
      #     PACKAGEJSON_DIR: js/plugins/chroma
      #   with:
      #     default: ${{ inputs.releaseType }}
      #     preid: ${{ inputs.preid }}
      #     commit-message: 'chore: bump genkitx-chromadb version to {{version}}'
      #     tag-prefix:  'genkitx-chromadb'
      # - name: 'js/plugins/dev-local-vectorstore version bump'
      #   uses: 'phips28/gh-action-bump-version@master'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
      #     PACKAGEJSON_DIR: js/plugins/dev-local-vectorstore
      #   with:
      #     default: ${{ inputs.releaseType }}
      #     preid: ${{ inputs.preid }}
      #     commit-message: 'chore: bump @genkit-ai/dev-local-vectorstore version to {{version}}'
      #     tag-prefix:  '@genkit-ai/dev-local-vectorstore@'
      # - name: 'js/plugins/dotprompt version bump'
      #   uses: 'phips28/gh-action-bump-version@master'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
      #     PACKAGEJSON_DIR: js/plugins/dotprompt
      #   with:
      #     default: ${{ inputs.releaseType }}
      #     preid: ${{ inputs.preid }}
      #     commit-message: 'chore: bump @genkit-ai/dotprompt version to {{version}}'
      #     tag-prefix:  '@genkit-ai/dotprompt@'
      - name: 'js/plugins/evaluators version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: js/plugins/evaluators
        with:
          default: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump @genkit-ai/evaluator version to {{version}}'
          tag-prefix:  '@genkit-ai/evaluator@'
      - name: 'js/plugins/firebase version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: js/plugins/firebase
        with:
          default: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump @genkit-ai/firebase version to {{version}}'
          tag-prefix:  '@genkit-ai/firebase@'
      - name: 'js/plugins/google-cloud version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: js/plugins/google-cloud
        with:
          default: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump @genkit-ai/google-cloud version to {{version}}'
          tag-prefix:  '@genkit-ai/google-cloud@'
      - name: 'js/plugins/googleai version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: js/plugins/googleai
        with:
          default: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump @genkit-ai/googleai version to {{version}}'
          tag-prefix:  '@genkit-ai/googleai@'
      - name: 'js/plugins/langchain version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: js/plugins/langchain
        with:
          default: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump genkitx-langchain version to {{version}}'
          tag-prefix:  'genkitx-langchain@'
      - name: 'js/plugins/ollama version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: js/plugins/ollama
        with:
          default: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump genkitx-ollama version to {{version}}'
          tag-prefix:  'genkitx-ollama@'
      - name: 'js/plugins/pinecone version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: js/plugins/pinecone
        with:
          default: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump genkitx-pinecone version to {{version}}'
          tag-prefix:  'genkitx-pinecone@'
      - name: 'js/plugins/vertexai version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GENKIT_RELEASER_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: js/plugins/vertexai
        with:
          default: ${{ inputs.releaseType }}
          preid: ${{ inputs.preid }}
          commit-message: 'chore: bump @genkit-ai/vertexai version to {{version}}'
          tag-prefix:  '@genkit-ai/vertexai@'
