# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Release Genkit JS

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: Release tag
        type: choice
        default: next
        required: true
        options:
          - next
          - latest
        
jobs:
  build:
    name: Run build tasks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v3
    - name: Set up node v21
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'pnpm'
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Install dependencies
      run: pnpm install
    - name: Run build script
      run: pnpm build
    - name: Run js tests
      run: pnpm test:js
    - name: Validate working directory is clean
      run: .github/workflows/scripts/ensure-clean-working-tree.sh
    - name: Set up node v21
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'pnpm'
        registry-url: 'https://wombat-dressing-room.appspot.com/'
    - name: release script
      shell: bash
      run: RELEASE_BRANCH=${{ steps.extract_branch.outputs.branch }} RELEASE_TAG=${{ inputs.releaseTag }} scripts/release_main.sh
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
